### ISSUE TITLE
Dropdown changeHandler doesn't appear to work on Safari or Firefox

### ISSUE THREAD

**Issue by parkerpearson** [Pearson-Higher-Ed/compounds#86]
When I run the demo page on either Safari 10.1.2 or Firefox 55.0 and click on a `DropdownItem` of `type="button"` (for example the first item in the first example dropdown, shown in screenshot) it appears the changeHandler is not getting invoked, i.e. the item is not being marked as selected and nothing is being logged to the console.
<img width="534" alt="screen shot 2017-09-13 at 4 07 57 pm" src="https://user-images.githubusercontent.com/13319923/30403221-d5c89f7a-989d-11e7-8927-fbccfe4664ad.png">

I'm seeing similar behavior when using the dropdown on the design site. It does function as expected in Chrome.

**Comment by mhomolak** [comment]
Clicks are not being picked up, enter fires as expected.  I'll let Kiran & Hung know.

**Comment by loahou04** [comment]
PR has been created.  Issue as the way we were handling closing the dropdown when a user clicks outside of the dom.  I tried to make it efficient and make it so that i didn't have to create event listeners by using "onblur".  Onblur unfortunately causes some issues with timing which the workaround was to create a setTimeout of 0.  So now we care creating event listeners instead and just cleaning up after ourselves when the dropdown is unmounted.
